/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_akashbkumar_jni_EventLogReader */

#ifndef _Included_org_akashbkumar_jni_EventLogReader
#define _Included_org_akashbkumar_jni_EventLogReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_akashbkumar_jni_EventLogReader
 * Method:    getLogs
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_akashbkumar_jni_EventLogReader_getLogs
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
